# Generated by Django 3.1.7 on 2021-04-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='process_url',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='session_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
